PRAGMA journal_mode = WAL;
PRAGMA synchronous = OFF;
PRAGMA temp_store = MEMORY;
PRAGMA cache_size = -500000;

DROP TABLE IF EXISTS wordlist_stage1;
DROP TABLE IF EXISTS wordlist_stage2;
DROP TABLE IF EXISTS wordlist_stage3;
DROP TABLE IF EXISTS wordlist_full;

CREATE TABLE wordlist_stage1 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word TEXT UNIQUE NOT NULL,
    category TEXT DEFAULT 'subdomain'
);

CREATE TABLE wordlist_stage2 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word TEXT UNIQUE NOT NULL,
    category TEXT DEFAULT 'subdomain.subdomain'
);

CREATE TABLE wordlist_stage3 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word TEXT UNIQUE NOT NULL,
    category TEXT DEFAULT 'subdomain.subdomain.subdomain'
);

CREATE TABLE wordlist_full (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pattern TEXT UNIQUE NOT NULL,
    stage INTEGER,
    category TEXT
);

CREATE INDEX idx_s1_word ON wordlist_stage1(word);
CREATE INDEX idx_s2_word ON wordlist_stage2(word);
CREATE INDEX idx_s3_word ON wordlist_stage3(word);
CREATE INDEX idx_full_stage ON wordlist_full(stage);
CREATE INDEX idx_full_cat ON wordlist_full(category);

INSERT OR IGNORE INTO wordlist_stage1 (word) VALUES
('admin'),('administrator'),('adm'),('admin1'),('admin2'),('admin3'),('admin4'),('admin5'),
('admin6'),('admin7'),('admin8'),('admin9'),('admin10'),('admin11'),('admin12'),('admin13'),
('admin14'),('admin15'),('admin16'),('admin17'),('admin18'),('admin19'),('admin20'),
('admin21'),('admin22'),('admin23'),('admin24'),('admin25'),('admin26'),('admin27'),('admin28'),
('admin29'),('admin30'),('adminpanel'),('adminarea'),('admincp'),('adminer'),('adminer1'),
('adminer2'),('adminer3'),('adminer4'),('adminer5'),('adminer6'),('adminer7'),('adminer8'),
('adminlogin'),('adminlogin1'),('adminlogin2'),('admin-old'),('admin-old1'),('admin-old2'),
('admin-backup'),('admin-backup1'),('admin-backup2'),('admin-temp'),('admin-tmp'),
('admin-test'),('admin-test1'),('admin-test2'),('admin-dev'),('admin-dev1'),('admin-dev2'),
('admin-staging'),('admin-stg'),('admin-prod'),('admin-demo'),('admin-demo1'),
('admin2019'),('admin2020'),('admin2021'),('admin2022'),('admin2023'),('admin2024'),
('admin2025'),('admin2026'),('admin2027'),('admin-2020'),('admin-2021'),('admin-2022'),
('admin-2023'),('admin-2024'),('admin-2025'),('admin2024-old'),('admin2023-old'),
('administrator-old'),('administrator-backup'),('administrator-test'),('administrator-dev'),
('panel'),('panel1'),('panel2'),('panel3'),('panel4'),('panel5'),('panel6'),('panel7'),
('panel8'),('panel9'),('panel10'),('panel-old'),('panel-backup'),('panel-test'),('panel-dev'),
('manage'),('manager'),('management'),('management1'),('management2'),('cpanel'),
('cpanel1'),('cpanel2'),('cpanel3'),('cpanel-old'),('cpanel-backup'),
('whm'),('whm1'),('whm2'),('whm-old'),('whm-backup'),('dashboard'),('dashboard1'),
('dashboard2'),('dashboard-old'),('dashboard-backup'),('dashboard-test'),('dashboard-dev'),
('console'),('console1'),('console2'),('console-old'),('console-backup'),
('control'),('controller'),('controlpanel'),('controlpanel1'),('control-old'),
('portal'),('portal1'),('portal2'),('portal3'),('portal-old'),('portal-backup'),
('portal-test'),('portal-dev'),('portal-staging'),('backend'),('backend1'),('backend2'),
('backend-old'),('backend-backup'),('backend-test'),('backend-dev'),('backend-staging'),
('backoffice'),('backoffice1'),('backoffice2'),('backoffice-old'),('backoffice-backup'),
('cp'),('cp1'),('cp2'),('cp-old'),('cp-backup'),('webadmin'),('webadmin1'),('webadmin2'),
('webadmin-old'),('webadmin-backup'),('sysadmin'),('sysadmin1'),('sysadmin2'),
('sysadmin-old'),('sysadmin-backup'),('root'),('root1'),('root2'),('root3'),('root4'),
('root5'),('root-old'),('root-backup'),('root-temp'),('root-tmp'),('root-test'),('root-dev'),
('superuser'),('superuser1'),('superuser2'),('superuser-old'),('super'),('super1'),
('super-old'),('sys'),('system'),('system1'),('system2'),('system-old'),('system-backup'),
('system-test'),('system-dev'),('master'),('master1'),('master-old'),('master-backup'),
('owner'),('owner1'),('owner-old'),('operator'),('operator1'),('operator-old'),
('staff'),('staff1'),('staff-old'),('staff-backup'),('employee'),('employee1'),
('employee-old'),('employees'),('employees1'),('employees-old'),('hr'),('hr1'),
('hr-old'),('hr-backup'),('hr-test'),('hr-dev'),('payroll'),('payroll1'),('payroll-old'),
('payroll-backup'),('finance'),('finance1'),('finance-old'),('finance-backup'),
('finance-test'),('finance-dev'),('accounting'),('accounting1'),('accounting-old'),
('accounting-backup'),('audit'),('audit1'),('audit-old'),('audit-backup'),
('compliance'),('compliance1'),('compliance-old'),('legal'),('legal1'),('legal-old'),
('risk'),('risk1'),('risk-old'),('governance'),('governance1'),
('api'),('apis'),('api1'),('api2'),('api3'),('api4'),('api5'),('api6'),('api7'),
('api8'),('api9'),('api10'),('api11'),('api12'),('api13'),('api14'),('api15'),
('api16'),('api17'),('api18'),('api19'),('api20'),('api21'),('api22'),('api23'),
('api24'),('api25'),('api26'),('api27'),('api28'),('api29'),('api30'),
('api-old'),('api-old1'),('api-old2'),('api-old3'),('api-old4'),('api-old5'),
('api-backup'),('api-backup1'),('api-backup2'),('api-backup3'),('api-backup4'),
('api-temp'),('api-tmp'),('api-tmp1'),('api-tmp2'),('api-tmp3'),
('api-test'),('api-test1'),('api-test2'),('api-test3'),('api-test4'),('api-test5'),
('api-dev'),('api-dev1'),('api-dev2'),('api-dev3'),('api-dev4'),('api-dev5'),
('api-staging'),('api-staging1'),('api-staging2'),('api-staging3'),
('api-prod'),('api-prod1'),('api-prod2'),('api-prod3'),
('api-demo'),('api-demo1'),('api-demo2'),('api-beta'),('api-beta1'),('api-beta2'),
('api-alpha'),('api-alpha1'),('api-canary'),('api-canary1'),('api-nightly'),
('api-internal'),('api-internal1'),('api-internal2'),('api-internal-old'),
('api-external'),('api-external1'),('api-public'),('api-public1'),('api-private'),
('api-private1'),('api-private-old'),('api-admin'),('api-admin1'),('api-admin-old'),
('api-mobile'),('api-mobile1'),('api-mobile-old'),('api-web'),('api-web1'),
('api-partner'),('api-partner1'),('api-vendor'),('api-vendor1'),('api-client'),
('api-client1'),('api-legacy'),('api-legacy1'),('api-legacy2'),('api-legacy-old'),
('api-new'),('api-new1'),('api-next'),('api-next1'),('api-v1'),('api-v2'),('api-v3'),
('api-v4'),('api-v5'),('api-v6'),('api-v7'),('api-v8'),('api-v9'),('api-v10'),
('api-v1-old'),('api-v2-old'),('api-v3-old'),('apiv1'),('apiv2'),('apiv3'),('apiv4'),
('apiv5'),('apiv6'),('apiv7'),('apiv8'),('apiv9'),('apiv10'),
('rest'),('rest1'),('rest2'),('rest-old'),('restapi'),('restapi1'),('restapi-old'),
('graphql'),('graphql1'),('graphql2'),('graphql-old'),('graphql-backup'),
('gql'),('gql1'),('grpc'),('grpc1'),('grpc-old'),('gateway'),('gateway1'),
('gateway2'),('gateway-old'),('gateway-backup'),('gw'),('gw1'),('gw-old'),
('service'),('service1'),('service2'),('service-old'),('service-backup'),
('services'),('services1'),('services2'),('services-old'),('microservice'),
('microservice1'),('microservice-old'),('ms'),('ms1'),('ms2'),('ms-old'),
('webhook'),('webhook1'),('webhook-old'),('webhook-backup'),('webhooks'),
('webhooks1'),('hooks'),('hooks1'),('hooks-old'),('callback'),('callback1'),
('callback-old'),('callbacks'),('callbacks1'),('oauth'),('oauth1'),('oauth2'),
('oauth-old'),('oauth-backup'),('oauth2-old'),('auth'),('auth1'),('auth2'),
('auth-old'),('auth-backup'),('auth-test'),('auth-dev'),('auth-staging'),
('authn'),('authn1'),('authz'),('authz1'),('sso'),('sso1'),('sso2'),('sso-old'),
('sso-backup'),('sso-test'),('sso-dev'),('login'),('login1'),('login2'),('login3'),
('login4'),('login5'),('login-old'),('login-backup'),('login-test'),('login-dev'),
('signin'),('signin1'),('signin-old'),('signup'),('signup1'),('signup-old'),
('register'),('register1'),('register-old'),('token'),('token1'),('token-old'),
('tokens'),('tokens1'),('idp'),('idp1'),('idp-old'),('iam'),('iam1'),('iam-old'),
('jwt'),('jwt1'),('jwt-old'),('key'),('key1'),('key-old'),('keys'),('keys1'),
('keys-old'),('secret'),('secret1'),('secret-old'),('secret-backup'),
('secrets'),('secrets1'),('secrets-old'),('credential'),('credential1'),
('credential-old'),('credentials'),('credentials1'),('credentials-old'),
('passwd'),('passwd1'),('passwd-old'),('password'),('password1'),('password-old'),
('passwords'),('passwords1'),
('dev'),('development'),('develop'),('devel'),('developers'),('developer'),
('dev1'),('dev2'),('dev3'),('dev4'),('dev5'),('dev6'),('dev7'),('dev8'),('dev9'),
('dev10'),('dev11'),('dev12'),('dev13'),('dev14'),('dev15'),('dev16'),('dev17'),
('dev18'),('dev19'),('dev20'),('dev21'),('dev22'),('dev23'),('dev24'),('dev25'),
('dev26'),('dev27'),('dev28'),('dev29'),('dev30'),
('dev-old'),('dev-old1'),('dev-old2'),('dev-old3'),('dev-backup'),('dev-backup1'),
('dev-backup2'),('dev-temp'),('dev-tmp'),('dev-test'),('dev-test1'),('dev-staging'),
('dev-prod'),('dev-demo'),('dev-beta'),('dev-alpha'),('dev-canary'),
('dev-internal'),('dev-external'),('dev-public'),('dev-private'),
('dev-mobile'),('dev-web'),('dev-partner'),('dev-legacy'),('dev-new'),
('development1'),('development-old'),('development-backup'),('development-test'),
('staging'),('stage'),('stg'),('staging1'),('staging2'),('staging3'),('staging4'),
('staging5'),('staging6'),('staging7'),('staging8'),('staging9'),('staging10'),
('staging-old'),('staging-old1'),('staging-backup'),('staging-backup1'),
('staging-temp'),('staging-tmp'),('staging-test'),('staging-dev'),('staging-prod'),
('stage1'),('stage2'),('stage3'),('stage4'),('stage5'),('stage-old'),('stage-backup'),
('stg1'),('stg2'),('stg3'),('stg-old'),('stg-backup'),
('test'),('testing'),('tst'),('test1'),('test2'),('test3'),('test4'),('test5'),
('test6'),('test7'),('test8'),('test9'),('test10'),('test11'),('test12'),('test13'),
('test14'),('test15'),('test16'),('test17'),('test18'),('test19'),('test20'),
('test21'),('test22'),('test23'),('test24'),('test25'),('test26'),('test27'),
('test28'),('test29'),('test30'),
('test-old'),('test-old1'),('test-old2'),('test-backup'),('test-backup1'),
('test-temp'),('test-tmp'),('test-dev'),('test-staging'),('test-prod'),
('test-demo'),('test-beta'),('test-alpha'),('test-internal'),('test-external'),
('test-mobile'),('test-web'),('test-legacy'),('test-new'),('testing1'),
('testing-old'),('testing-backup'),('testing-test'),
('qa'),('qa1'),('qa2'),('qa3'),('qa4'),('qa5'),('qa6'),('qa7'),('qa8'),('qa9'),
('qa10'),('qa11'),('qa12'),('qa13'),('qa14'),('qa15'),('qa-old'),('qa-backup'),
('qa-test'),('qa-dev'),('qa-staging'),
('uat'),('uat1'),('uat2'),('uat3'),('uat4'),('uat5'),('uat6'),('uat7'),('uat8'),
('uat9'),('uat10'),('uat-old'),('uat-backup'),('uat-test'),('uat-dev'),
('sit'),('sit1'),('sit2'),('sit3'),('sit-old'),('sit-backup'),
('sandbox'),('sandbox1'),('sandbox2'),('sandbox3'),('sandbox-old'),('sandbox-backup'),
('sbx'),('sbx1'),('sbox'),('sbox1'),('sbox-old'),
('pre'),('pre1'),('pre2'),('pre-old'),('pre-backup'),('preprod'),('preprod1'),
('preprod2'),('preprod-old'),('preview'),('preview1'),('preview2'),('preview-old'),
('demo'),('demo1'),('demo2'),('demo3'),('demo4'),('demo5'),('demo6'),('demo7'),
('demo8'),('demo9'),('demo10'),('demo-old'),('demo-backup'),('demo-test'),
('beta'),('beta1'),('beta2'),('beta3'),('beta4'),('beta5'),('beta-old'),('beta-backup'),
('alpha'),('alpha1'),('alpha2'),('alpha3'),('alpha-old'),('alpha-backup'),
('canary'),('canary1'),('canary-old'),('nightly'),('nightly1'),('latest'),
('latest1'),('next'),('next1'),('next-old'),
('old'),('old1'),('old2'),('old3'),('old4'),('old5'),('old6'),('old7'),('old8'),
('old9'),('old10'),('old11'),('old12'),('old13'),('old14'),('old15'),('old16'),
('old17'),('old18'),('old19'),('old20'),('old21'),('old22'),('old23'),('old24'),
('old25'),('old26'),('old27'),('old28'),('old29'),('old30'),
('old-backup'),('old-backup1'),('old-temp'),('old-tmp'),('old-test'),('old-dev'),
('legacy'),('legacy1'),('legacy2'),('legacy3'),('legacy4'),('legacy5'),('legacy6'),
('legacy7'),('legacy8'),('legacy9'),('legacy10'),
('legacy-old'),('legacy-backup'),('legacy-temp'),('legacy-test'),('legacy-dev'),
('v1'),('v2'),('v3'),('v4'),('v5'),('v6'),('v7'),('v8'),('v9'),('v10'),
('v11'),('v12'),('v13'),('v14'),('v15'),('v16'),('v17'),('v18'),('v19'),('v20'),
('new'),('new1'),('new-old'),('new-backup'),('temp'),('temp1'),('temp2'),('temp-old'),
('tmp'),('tmp1'),('tmp2'),('tmp3'),('tmp4'),('tmp5'),('tmp-old'),('tmp-backup'),
('scratch'),('scratch1'),('scratch-old'),('lab'),('lab1'),('lab2'),('lab-old'),
('labs'),('labs1'),('labs-old'),('research'),('research1'),('research-old'),
('rnd'),('rnd1'),('rnd-old'),('poc'),('poc1'),('poc2'),('poc-old'),
('prototype'),('prototype1'),('prototype-old'),('experimental'),('experimental1'),
('exp'),('exp1'),('exp-old'),
('mail'),('mail1'),('mail2'),('mail3'),('mail4'),('mail5'),('mail6'),('mail7'),
('mail8'),('mail9'),('mail10'),('mail11'),('mail12'),('mail13'),('mail14'),('mail15'),
('mail-old'),('mail-old1'),('mail-backup'),('mail-backup1'),('mail-temp'),('mail-tmp'),
('mail-test'),('mail-dev'),('mail-staging'),('mail-prod'),('mail-demo'),
('smtp'),('smtp1'),('smtp2'),('smtp3'),('smtp4'),('smtp5'),('smtp6'),('smtp7'),
('smtp8'),('smtp9'),('smtp10'),('smtp-old'),('smtp-backup'),('smtp-test'),
('imap'),('imap1'),('imap2'),('imap3'),('imap4'),('imap5'),('imap-old'),('imap-backup'),
('pop'),('pop1'),('pop2'),('pop3'),('pop4'),('pop5'),('pop-old'),('pop-backup'),
('webmail'),('webmail1'),('webmail2'),('webmail-old'),('webmail-backup'),
('email'),('email1'),('email2'),('email3'),('email4'),('email5'),('email-old'),
('email-backup'),('mx'),('mx1'),('mx2'),('mx3'),('mx4'),('mx5'),('mx6'),('mx7'),
('mx8'),('mx9'),('mx10'),('mx-old'),('mx-backup'),('relay'),('relay1'),('relay2'),
('relay3'),('relay4'),('relay5'),('relay-old'),('relay-backup'),
('ns'),('ns1'),('ns2'),('ns3'),('ns4'),('ns5'),('ns6'),('ns7'),('ns8'),('ns9'),
('ns10'),('ns-old'),('dns'),('dns1'),('dns2'),('dns3'),('dns4'),('dns5'),('dns6'),
('dns7'),('dns8'),('dns9'),('dns10'),('dns-old'),('dns-backup'),
('resolver'),('resolver1'),('resolver2'),('resolver-old'),
('ftp'),('ftp1'),('ftp2'),('ftp3'),('ftp4'),('ftp5'),('ftp6'),('ftp7'),('ftp8'),
('ftp9'),('ftp10'),('ftp-old'),('ftp-backup'),('ftp-test'),('ftp-dev'),
('sftp'),('sftp1'),('sftp2'),('sftp-old'),('sftp-backup'),
('ftps'),('ftps1'),('ftps-old'),('files'),('files1'),('files2'),('files3'),
('files4'),('files5'),('files-old'),('files-backup'),('files-test'),
('file'),('file1'),('file2'),('file-old'),('file-backup'),
('upload'),('upload1'),('upload-old'),('upload-backup'),('uploads'),('uploads1'),
('uploads2'),('uploads-old'),('uploads-backup'),
('download'),('download1'),('download-old'),('downloads'),('downloads1'),
('share'),('share1'),('share-old'),('share-backup'),('sharing'),('sharing1'),
('shared'),('shared1'),('shared-old'),
('vpn'),('vpn1'),('vpn2'),('vpn3'),('vpn4'),('vpn5'),('vpn6'),('vpn7'),('vpn8'),
('vpn9'),('vpn10'),('vpn11'),('vpn12'),('vpn13'),('vpn14'),('vpn15'),
('vpn-old'),('vpn-backup'),('vpn-temp'),('vpn-test'),('vpn-dev'),
('openvpn'),('openvpn1'),('openvpn-old'),('wireguard'),('wireguard1'),
('wireguard-old'),('ipsec'),('ipsec1'),('ipsec-old'),
('rdp'),('rdp1'),('rdp2'),('rdp-old'),('rdp-backup'),
('ssh'),('ssh1'),('ssh2'),('ssh3'),('ssh4'),('ssh5'),('ssh6'),('ssh7'),('ssh8'),
('ssh9'),('ssh10'),('ssh-old'),('ssh-backup'),('ssh-test'),('ssh-dev'),
('bastion'),('bastion1'),('bastion2'),('bastion3'),('bastion4'),('bastion5'),
('bastion-old'),('bastion-backup'),('jump'),('jump1'),('jump2'),('jump-old'),
('jumpbox'),('jumpbox1'),('jumpbox-old'),
('proxy'),('proxy1'),('proxy2'),('proxy3'),('proxy4'),('proxy5'),('proxy6'),
('proxy7'),('proxy8'),('proxy9'),('proxy10'),('proxy-old'),('proxy-backup'),
('proxies'),('proxies1'),('proxies-old'),('squid'),('squid1'),('squid-old'),
('load'),('load1'),('load-old'),('lb'),('lb1'),('lb2'),('lb3'),('lb4'),('lb5'),
('lb-old'),('lb-backup'),('haproxy'),('haproxy1'),('haproxy-old'),
('nginx'),('nginx1'),('nginx-old'),('apache'),('apache1'),('apache-old'),
('httpd'),('httpd1'),('iis'),('iis1'),
('cloud'),('cloud1'),('cloud-old'),('cloud-backup'),
('aws'),('aws1'),('aws2'),('aws3'),('aws4'),('aws5'),('aws-old'),('aws-backup'),
('azure'),('azure1'),('azure2'),('azure3'),('azure-old'),('azure-backup'),
('gcp'),('gcp1'),('gcp2'),('gcp3'),('gcp-old'),('gcp-backup'),
('gcloud'),('gcloud1'),('gcloud-old'),('oci'),('oci1'),('oci-old'),
('do'),('do1'),('do-old'),('digitalocean'),('digitalocean1'),('linode'),('vultr'),
('s3'),('s3-1'),('s3-2'),('s3-3'),('s3-4'),('s3-5'),('s3-old'),('s3-backup'),
('bucket'),('bucket1'),('bucket2'),('bucket3'),('bucket4'),('bucket5'),
('bucket-old'),('bucket-backup'),('buckets'),('buckets1'),('buckets-old'),
('storage'),('storage1'),('storage2'),('storage3'),('storage4'),('storage5'),
('storage-old'),('storage-backup'),('blob'),('blob1'),('blob2'),('blob-old'),
('cdn'),('cdn1'),('cdn2'),('cdn3'),('cdn4'),('cdn5'),('cdn6'),('cdn7'),('cdn8'),
('cdn9'),('cdn10'),('cdn-old'),('cdn-backup'),('edge'),('edge1'),('edge2'),
('edge-old'),('static'),('static1'),('static2'),('static3'),('static4'),
('static5'),('static-old'),('static-backup'),('assets'),('assets1'),('assets2'),
('assets3'),('assets4'),('assets5'),('assets-old'),('assets-backup'),
('img'),('img1'),('img2'),('img3'),('img4'),('img5'),('img-old'),('img-backup'),
('images'),('images1'),('images2'),('images-old'),('media'),('media1'),
('media2'),('media3'),('media4'),('media5'),('media-old'),('media-backup'),
('video'),('video1'),('video2'),('video3'),('video4'),('video5'),('video-old'),
('data'),('data1'),('data2'),('data3'),('data4'),('data5'),('data-old'),
('data-backup'),('data-test'),('data-dev'),
('app'),('apps'),('application'),('app1'),('app2'),('app3'),('app4'),('app5'),
('app6'),('app7'),('app8'),('app9'),('app10'),('app11'),('app12'),('app13'),
('app14'),('app15'),('app16'),('app17'),('app18'),('app19'),('app20'),
('app-old'),('app-old1'),('app-backup'),('app-backup1'),('app-temp'),('app-tmp'),
('app-test'),('app-dev'),('app-staging'),('app-prod'),('app-demo'),('app-beta'),
('app-internal'),('app-external'),('app-private'),('app-mobile'),('app-web'),
('app-legacy'),('app-new'),('application1'),('application-old'),('apps-old'),
('web'),('web1'),('web2'),('web3'),('web4'),('web5'),('web6'),('web7'),('web8'),
('web9'),('web10'),('web-old'),('web-old1'),('web-backup'),('web-temp'),
('web-test'),('web-dev'),('web-staging'),('web-prod'),('web-demo'),
('www'),('www1'),('www2'),('www3'),('www4'),('www5'),('www6'),('www7'),('www8'),
('www9'),('www10'),('www-old'),('www-old1'),('www-backup'),
('site'),('site1'),('site2'),('site3'),('site4'),('site5'),('site-old'),
('site-backup'),('shop'),('shop1'),('shop2'),('shop-old'),('shop-backup'),
('store'),('store1'),('store2'),('store-old'),('store-backup'),
('ecommerce'),('ecommerce1'),('ecommerce-old'),('cart'),('cart1'),('cart-old'),
('checkout'),('checkout1'),('checkout-old'),('checkout-backup'),
('payment'),('payment1'),('payment2'),('payment-old'),('payment-backup'),
('pay'),('pay1'),('pay2'),('pay-old'),('pay-backup'),('payments'),('payments1'),
('billing'),('billing1'),('billing-old'),('billing-backup'),('invoice'),
('invoice1'),('invoice-old'),('invoices'),('invoices1'),('finance'),
('account'),('account1'),('account-old'),('accounts'),('accounts1'),
('accounts-old'),('user'),('user1'),('user2'),('user-old'),('user-backup'),
('users'),('users1'),('users-old'),('profile'),('profile1'),('profile-old'),
('profiles'),('profiles1'),('member'),('member1'),('member-old'),('members'),
('members1'),('customer'),('customer1'),('customer-old'),('customers'),
('customers1'),('client'),('client1'),('client-old'),('clients'),('clients1'),
('partner'),('partner1'),('partner-old'),('partners'),('partners1'),
('vendor'),('vendor1'),('vendor-old'),('vendors'),('vendors1'),
('support'),('support1'),('support-old'),('help'),('help1'),('help-old'),
('helpdesk'),('helpdesk1'),('helpdesk-old'),('ticket'),('ticket1'),('ticket-old'),
('tickets'),('tickets1'),('crm'),('crm1'),('crm-old'),('erp'),('erp1'),('erp-old'),
('intranet'),('intranet1'),('intranet-old'),('extranet'),('extranet1'),
('internal'),('internal1'),('internal-old'),('corp'),('corp1'),('corp-old'),
('corporate'),('corporate1'),('office'),('office1'),('office-old'),('ops'),
('ops1'),('ops-old'),
('monitor'),('monitor1'),('monitor-old'),('monitoring'),('monitoring1'),
('monitoring-old'),('grafana'),('grafana1'),('grafana2'),('grafana3'),
('grafana-old'),('grafana-backup'),('kibana'),('kibana1'),('kibana2'),('kibana3'),
('kibana-old'),('kibana-backup'),('prometheus'),('prometheus1'),('prometheus2'),
('prometheus-old'),('alertmanager'),('alertmanager1'),('zabbix'),('zabbix1'),
('zabbix-old'),('nagios'),('nagios1'),('nagios-old'),('sensu'),('sensu1'),
('datadog'),('datadog1'),('newrelic'),('newrelic1'),('sentry'),('sentry1'),
('sentry-old'),('logs'),('logs1'),('logs-old'),('log'),('log1'),('log-old'),
('logging'),('logging1'),('logging-old'),('elk'),('elk1'),('elk-old'),
('elastic'),('elastic1'),('elasticsearch'),('elasticsearch1'),('elasticsearch-old'),
('splunk'),('splunk1'),('splunk-old'),('graylog'),('graylog1'),('stats'),
('stats1'),('stats-old'),('status'),('status1'),('status-old'),('health'),
('health1'),('health-old'),('metrics'),('metrics1'),('metrics-old'),
('trace'),('trace1'),('tracing'),('tracing1'),('jaeger'),('jaeger1'),
('zipkin'),('zipkin1'),
('jenkins'),('jenkins1'),('jenkins2'),('jenkins3'),('jenkins4'),('jenkins5'),
('jenkins-old'),('jenkins-backup'),('jenkins-test'),('jenkins-dev'),
('ci'),('ci1'),('ci2'),('ci3'),('ci4'),('ci5'),('ci-old'),('ci-backup'),
('cd'),('cd1'),('cd2'),('cd-old'),('cd-backup'),
('build'),('build1'),('build-old'),('build-backup'),('builder'),('builder1'),
('bamboo'),('bamboo1'),('teamcity'),('teamcity1'),('drone'),('drone1'),
('argo'),('argo1'),('argocd'),('argocd1'),('argocd-old'),('gitlab'),('gitlab1'),
('gitlab2'),('gitlab3'),('gitlab-old'),('gitlab-backup'),('gitlab-test'),
('github'),('github1'),('github-old'),('gitea'),('gitea1'),('gogs'),('gogs1'),
('bitbucket'),('bitbucket1'),('bitbucket-old'),('git'),('git1'),('git2'),
('git-old'),('git-backup'),('repo'),('repo1'),('repo-old'),('repos'),('repos1'),
('repos-old'),('registry'),('registry1'),('registry2'),('registry-old'),
('registry-backup'),('harbor'),('harbor1'),('harbor-old'),('nexus'),('nexus1'),
('nexus2'),('nexus-old'),('nexus-backup'),('artifactory'),('artifactory1'),
('artifactory-old'),('sonar'),('sonar1'),('sonar-old'),('sonarqube'),
('sonarqube1'),('ansible'),('ansible1'),('ansible-old'),('terraform'),
('terraform1'),('terraform-old'),('vault'),('vault1'),('vault2'),('vault-old'),
('vault-backup'),('consul'),('consul1'),('consul-old'),('nomad'),('nomad1'),
('nomad-old'),('k8s'),('k8s1'),('k8s-old'),('kubernetes'),('kubernetes1'),
('kubernetes-old'),('kube'),('kube1'),('kube-old'),('rancher'),('rancher1'),
('rancher-old'),('docker'),('docker1'),('docker-old'),('swarm'),('swarm1'),
('db'),('db1'),('db2'),('db3'),('db4'),('db5'),('db6'),('db7'),('db8'),('db9'),
('db10'),('db11'),('db12'),('db13'),('db14'),('db15'),('db16'),('db17'),('db18'),
('db19'),('db20'),('db-old'),('db-backup'),('db-temp'),('db-tmp'),('db-test'),
('db-dev'),('db-staging'),('db-prod'),('db-demo'),('database'),('database1'),
('database-old'),('database-backup'),('mysql'),('mysql1'),('mysql2'),('mysql3'),
('mysql4'),('mysql5'),('mysql-old'),('mysql-backup'),('mysql-test'),('mysql-dev'),
('mariadb'),('mariadb1'),('mariadb-old'),('postgres'),('postgres1'),('postgres2'),
('postgres-old'),('postgres-backup'),('postgresql'),('postgresql1'),
('postgresql-old'),('pgsql'),('pgsql1'),('pgsql-old'),('mongo'),('mongo1'),
('mongo2'),('mongo-old'),('mongo-backup'),('mongodb'),('mongodb1'),('mongodb-old'),
('redis'),('redis1'),('redis2'),('redis3'),('redis-old'),('redis-backup'),
('redis-test'),('redis-dev'),('memcached'),('memcached1'),('memcached-old'),
('cassandra'),('cassandra1'),('cassandra-old'),('couchdb'),('couchdb1'),
('couchbase'),('couchbase1'),('neo4j'),('neo4j1'),('influx'),('influx1'),
('influx-old'),('influxdb'),('influxdb1'),('clickhouse'),('clickhouse1'),
('sql'),('sql1'),('sql-old'),('sqlserver'),('sqlserver1'),('mssql'),('mssql1'),
('mssql-old'),('oracle'),('oracle1'),('oracle-old'),('phpmyadmin'),
('phpmyadmin1'),('phpmyadmin2'),('phpmyadmin-old'),('phpmyadmin-backup'),
('pma'),('pma1'),('pma-old'),('adminer'),('adminer-old'),('pgadmin'),
('pgadmin1'),('pgadmin-old'),
('security'),('security1'),('security-old'),('sec'),('sec1'),('sec-old'),
('secure'),('secure1'),('secure-old'),('ssl'),('ssl1'),('ssl-old'),
('tls'),('tls1'),('cert'),('cert1'),('cert-old'),('ca'),('ca1'),('ca-old'),
('pki'),('pki1'),('pki-old'),('ocsp'),('ocsp1'),('crl'),('crl1'),
('waf'),('waf1'),('waf-old'),('firewall'),('firewall1'),('firewall-old'),
('fw'),('fw1'),('fw-old'),('ids'),('ids1'),('ids-old'),('ips'),('ips1'),
('ips-old'),('siem'),('siem1'),('siem-old'),('soc'),('soc1'),('soc-old'),
('scanner'),('scanner1'),('scanner-old'),('antivirus'),('antivirus1'),
('av'),('av1'),('edr'),('edr1'),('xdr'),('xdr1'),('dlp'),('dlp1'),
('honeypot'),('honeypot1'),
('blog'),('blog1'),('blog2'),('blog-old'),('blog-backup'),('news'),('news1'),
('news-old'),('press'),('press1'),('press-old'),('media'),('media1'),
('marketing'),('marketing1'),('marketing-old'),('ads'),('ads1'),('ads-old'),
('tracking'),('tracking1'),('analytics'),('analytics1'),('analytics-old'),
('docs'),('docs1'),('docs2'),('docs-old'),('docs-backup'),('doc'),('doc1'),
('documentation'),('documentation1'),('documentation-old'),('wiki'),('wiki1'),
('wiki-old'),('kb'),('kb1'),('knowledge'),('knowledge1'),('forum'),('forum1'),
('forum-old'),('community'),('community1'),('community-old'),('discuss'),
('discuss1'),('careers'),('careers1'),('careers-old'),('jobs'),('jobs1'),
('jobs-old'),('recruit'),('recruit1'),('training'),('training1'),('learn'),
('learn1'),('edu'),('edu1'),('events'),('events1'),('events-old'),
('meet'),('meet1'),('meet-old'),('zoom'),('zoom1'),('chat'),('chat1'),
('chat-old'),('im'),('im1'),('messenger'),('messenger1'),('sms'),('sms1'),
('sms-old'),('voice'),('voice1'),('call'),('call1'),('m'),('m1'),('m-old'),
('mobile'),('mobile1'),('mobile2'),('mobile-old'),('wap'),('wap1'),
('ios'),('ios1'),('ios-old'),('android'),('android1'),('android-old'),
('tablet'),('tablet1'),
('archive'),('archives'),('archive1'),('archive2'),('archive-old'),
('archive-backup'),('backup'),('backup1'),('backup2'),('backup3'),('backup4'),
('backup5'),('backup6'),('backup7'),('backup8'),('backup9'),('backup10'),
('backup-old'),('backup-temp'),('backups'),('backups1'),('backups2'),
('backups-old'),('bak'),('bak1'),('bak2'),('bak3'),('bak-old'),
('dump'),('dump1'),('dump2'),('dump3'),('dump-old'),('dumps'),('dumps1'),
('dumps-old'),('trash'),('trash1'),('deprecated'),('deprecated1'),
('retired'),('retired1'),('inactive'),('inactive1'),('unused'),('unused1'),
('spare'),('spare1'),('spare2'),('spare-old'),('obsolete'),('obsolete1'),
('ancient'),('ancient1'),('historical'),('historical1'),
('prod'),('production'),('prd'),('prod1'),('prod2'),('prod3'),('prod4'),
('prod5'),('prod6'),('prod7'),('prod8'),('prod9'),('prod10'),('prod11'),
('prod12'),('prod13'),('prod14'),('prod15'),('prod-old'),('prod-backup'),
('production1'),('production2'),('production3'),('production-old'),
('production-backup'),('prd1'),('prd2'),('prd3'),('prd4'),('prd5'),('prd-old'),
('live'),('live1'),('live2'),('live3'),('live4'),('live5'),('live-old'),
('live-backup'),
('internal2'),('internal3'),('internal4'),('internal5'),('internal6'),
('internal7'),('internal8'),('internal9'),('internal10'),('internal-old'),
('internal-backup'),('intranet2'),('intranet3'),('intranet-old'),
('private'),('priv'),('priv1'),('hidden'),('hidden1'),('hidden-old'),
('us'),('us1'),('us2'),('us3'),('us4'),('us5'),('us-old'),
('eu'),('eu1'),('eu2'),('eu3'),('eu4'),('eu5'),('eu-old'),
('ap'),('ap1'),('ap2'),('apac'),('apac1'),('sg'),('sg1'),('sg-old'),
('jp'),('jp1'),('au'),('au1'),('uk'),('uk1'),('uk-old'),
('id'),('id1'),('my'),('my1'),('th'),('th1'),('in'),('in1'),
('cn'),('cn1'),('kr'),('kr1'),('hk'),('hk1'),('tw'),('tw1'),
('vn'),('vn1'),('ph'),('ph1'),('br'),('br1'),('mx'),('mx1'),
('de'),('de1'),('fr'),('fr1'),('it'),('it1'),('es'),('es1'),
('nl'),('nl1'),('se'),('se1'),('no'),('no1'),('dk'),('dk1'),
('fi'),('fi1'),('pl'),('pl1'),('ru'),('ru1'),('tr'),('tr1'),
('za'),('za1'),('eg'),('eg1'),('ae'),('ae1'),('sa'),('sa1'),('il'),('il1'),
('a'),('b'),('c'),('d'),('e'),('f'),('g'),('h'),('i'),('j'),('k'),('l'),
('n'),('o'),('p'),('q'),('r'),('s'),('t'),('u'),('v'),('w'),('x'),('y'),('z'),
('aa'),('bb'),('cc'),('dd'),('ee'),('ff'),('gg'),('hh'),('ii'),('jj'),('kk'),
('ll'),('mm'),('nn'),('oo'),('pp'),('qq'),('rr'),('ss'),('tt'),('uu'),('vv'),
('ww'),('xx'),('yy'),('zz'),
('test123'),('test1234'),('test12345'),('temp123'),('tmp123'),('admin123'),
('admin1234'),('root123'),('root1234'),('password123'),('qwerty'),('qwerty123'),
('abc123'),('abc1234'),('dev123'),('dev1234'),('demo123'),('staging123'),
('prod123'),('qa123'),('uat123'),('backup123'),('secret123'),('login123'),
('vpn123'),('smtp123'),('ftp123'),('mail123'),('ns123'),('dns123'),
('test2020'),('test2021'),('test2022'),('test2023'),('test2024'),('test2025'),
('test2026'),('dev2020'),('dev2021'),('dev2022'),('dev2023'),('dev2024'),
('dev2025'),('dev2026'),('admin2020'),('admin2021'),('admin2022'),('admin2023'),
('admin2024'),('admin2025'),('admin2026'),('staging2020'),('staging2021'),
('staging2022'),('staging2023'),('staging2024'),('staging2025'),('staging2026'),
('api2020'),('api2021'),('api2022'),('api2023'),('api2024'),('api2025'),('api2026'),
('backup2020'),('backup2021'),('backup2022'),('backup2023'),('backup2024'),
('backup2025'),('backup2026'),('prod2020'),('prod2021'),('prod2022'),
('prod2023'),('prod2024'),('prod2025'),('prod2026'),
('test-temp'),('test-tmp'),('test-old'),('test-backup'),('test2-old'),
('test3-old'),('test4-old'),('test5-old'),('dev-temp'),('dev-tmp'),
('dev2-old'),('dev3-old'),('dev4-old'),('dev5-old'),('staging-temp'),
('staging-tmp'),('staging2-old'),('staging3-old'),('api-temp'),('api-tmp'),
('api2-old'),('api3-old'),('api4-old'),('api5-old'),('admin-temp'),
('admin-tmp'),('admin2-old'),('admin3-old'),('admin4-old'),
('localhost'),('local'),('local1'),('local-old'),('localhost1'),('localhost-old'),
('staging-old-temp'),('dev-old-temp'),('test-old-temp'),('api-old-temp'),
('legacy-old'),('legacy-temp'),('legacy-tmp'),('old-temp'),('old-tmp'),
('nobody'),('nobody1'),('unknown'),('unknown1'),('none'),('none1'),
('null'),('null1'),('undefined'),('undefined1'),('void'),('void1'),
('todo'),('todo1'),('fixme'),('fixme1'),('xxx'),('xxx1'),('yyy'),('yyy1'),
('zzz'),('zzz1'),('aaa'),('aaa1'),('bbb'),('bbb1'),('ccc'),('ccc1'),
('temp1'),('temp2'),('temp3'),('temp4'),('temp5'),('temp6'),('temp7'),
('temp8'),('temp9'),('temp10'),('tmp6'),('tmp7'),('tmp8'),('tmp9'),('tmp10'),
('trash1'),('trash2'),('trash3'),('trash4'),('trash5'),
('junk'),('junk1'),('junk-old'),('rubbish'),('garbage'),('waste'),
('testing-old'),('testing-temp'),('testing-backup'),('testing-dev'),
('oldtesting'),('devtesting'),('newtesting'),('tmptesting'),
('mytest'),('yourtest'),('sometest'),('anytest'),('justtest'),
('mydomain'),('yourdomain'),('somedomain'),('anydomain'),('justdomain'),
('myapp'),('yourapp'),('someapp'),('anyapp'),('justapp'),
('myapi'),('yourapi'),('someapi'),('anyapi'),('justapi'),
('myadmin'),('youradmin'),('someadmin'),('anyadmin'),('justadmin'),
('mydev'),('yourdev'),('somedev'),('anydev'),('justdev'),
('myprod'),('yourprod'),('someprod'),('anyprod'),('justprod'),
('keepme'),('keepme1'),('ignoreme'),('ignoreme1'),('deleteme'),('deleteme1'),
('removeme'),('removeme1'),('dontuse'),('dontuse1'),('notused'),('notused1'),
('unused1'),('unused2'),('unused3'),('unused4'),('unused5'),
('spare3'),('spare4'),('spare5'),('spare6'),('spare7'),('spare8'),
('demo2020'),('demo2021'),('demo2022'),('demo2023'),('demo2024'),('demo2025'),
('demo2026'),('legacy2020'),('legacy2021'),('legacy2022'),('legacy2023'),
('legacy2024'),('legacy2025'),('legacy2026'),
('qa2020'),('qa2021'),('qa2022'),('qa2023'),('qa2024'),('qa2025'),('qa2026'),
('uat2020'),('uat2021'),('uat2022'),('uat2023'),('uat2024'),('uat2025'),('uat2026'),
('preprod2020'),('preprod2021'),('preprod2022'),('preprod2023'),('preprod2024'),
('preprod2025'),('preprod2026'),('staging-old1'),('staging-old2'),('staging-old3'),
('dev-old1'),('dev-old2'),('dev-old3'),('api-old1'),('api-old2'),('api-old3'),
('test-old1'),('test-old2'),('test-old3'),('admin-old1'),('admin-old2'),('admin-old3');

INSERT OR IGNORE INTO wordlist_stage2 (word)
SELECT a.word || '.' || b.word
FROM wordlist_stage1 a
CROSS JOIN wordlist_stage1 b
WHERE a.word != b.word
ORDER BY a.id, b.id
LIMIT 40000;

INSERT OR IGNORE INTO wordlist_stage3 (word)
SELECT a.word || '.' || b.word || '.' || c.word
FROM wordlist_stage1 a
CROSS JOIN wordlist_stage1 b
CROSS JOIN wordlist_stage1 c
WHERE a.word != b.word
  AND b.word != c.word
  AND a.word != c.word
  AND a.word IN ('dev','test','staging','qa','uat','prod','old','legacy','backup','demo','beta','sandbox','preprod','stage','stg','tmp','temp','new','live','v1','v2','internal','corp','private','admin','api','pre','sit','prd','production')
  AND b.word IN ('dev','test','staging','qa','uat','prod','old','legacy','backup','internal','corp','private','secret','hidden','v1','v2','temp','tmp','pre','sit','admin','api')
  AND c.word IN ('api','app','web','admin','db','mail','vpn','auth','portal','internal','gateway','service','login','sso','dashboard','panel','console','files','ftp','ssh','user','accounts','payment','billing','redis','mysql','mongo','postgres','jenkins','gitlab','kibana','grafana','prometheus','vault','consul','s3','bucket','storage','cdn','static','assets','media','img','video','data','security','waf','ldap','ad','radius','tacacs','smtp','imap','pop','ns','dns','mx','relay','proxy','lb','nginx','apache','httpd','docker','k8s','kubernetes','nexus','sonar','artifactory','harbor','registry','repo','git')
ORDER BY a.id, b.id, c.id
LIMIT 25000;

INSERT OR IGNORE INTO wordlist_full (pattern,stage,category)
SELECT word,1,'subdomain' FROM wordlist_stage1;

INSERT OR IGNORE INTO wordlist_full (pattern,stage,category)
SELECT word,2,'subdomain.subdomain' FROM wordlist_stage2;

INSERT OR IGNORE INTO wordlist_full (pattern,stage,category)
SELECT word,3,'subdomain.subdomain.subdomain' FROM wordlist_stage3;

VACUUM;
ANALYZE;

SELECT 'STAGE1 (subdomain)' AS kategori, COUNT(*) AS jumlah FROM wordlist_stage1
UNION ALL
SELECT 'STAGE2 (subdomain.subdomain)', COUNT(*) FROM wordlist_stage2
UNION ALL
SELECT 'STAGE3 (subdomain.subdomain.subdomain)', COUNT(*) FROM wordlist_stage3
UNION ALL
SELECT 'TOTAL FULL', COUNT(*) FROM wordlist_full;